var VARIATION_ZH = {
    "→": "右箭头",
    "←": "左箭头",
    "← →": "左右箭头",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "Aqua": "水色",
    "Aqua roof": "水色屋顶",
    "Ash": "灰烬",
    "Ash brown": "灰棕色",
    "Ash green": "灰绿色",
    "Avocado": "牛油果色",
    "Azalea": "杜鹃花",
    "Baby blue": "婴儿蓝",
    "Baby gray": "婴儿灰",
    "Baby green": "婴儿绿",
    "Baby mint": "婴儿薄荷",
    "Baby orange": "婴儿橙",
    "Baby pink": "婴儿粉",
    "Baby purple": "婴儿紫",
    "Baby yellow": "婴儿黄",
    "Bamboo": "竹色",
    "Beige & green": "米色绿",
    "Beige & navy": "米色藏青",
    "Beige & white": "米白",
    "Berry red": "浆果红",
    "Black & blue": "黑蓝",
    "Black & gray": "黑灰",
    "Black & orange": "黑橙",
    "Black & red": "黑红",
    "Black & silver": "黑银",
    "Black & white": "黑白",
    "Black & yellow": "黑黄",
    "Black bass": "黑鲈鱼",
    "Black cherry": "黑樱桃",
    "Black granite": "黑花岗岩",
    "Black marble": "黑大理石",
    "Black necktie": "黑领带",
    "Black ribbons": "黑丝带",
    "Black roof": "黑屋顶",
    "Black sesame": "黑芝麻",
    "Black wood & tile": "黑木瓷砖",
    "Black, coral & pink": "黑珊瑚粉",
    "Blood orange": "血橙",
    "Blooming": "盛开",
    "Blue & black": "蓝黑",
    "Blue & gray": "蓝灰",
    "Blue & green": "蓝绿",
    "Blue & orange": "蓝橙",
    "Blue & purple": "蓝紫",
    "Blue & red": "蓝红",
    "Blue & white": "蓝白",
    "Blue & yellow": "蓝黄",
    "Blue cat": "蓝猫",
    "Blue marlin": "蓝枪鱼",
    "Blue ribbons": "蓝丝带",
    "Blue roof": "蓝屋顶",
    "Blue with flowers": "蓝花",
    "Blue with yellow ribbon": "蓝黄丝带",
    "Blueberries": "蓝莓",
    "Blue-gray": "蓝灰",
    "Blue-striped necktie": "蓝条纹领带",
    "Boat": "船",
    "Boating stripes": "划船条纹",
    "Borscht": "罗宋汤",
    "Bouquet": "花束",
    "Brainstorming meeting": "头脑风暴",
    "Brick house": "砖房",
    "Brown & black": "棕黑",
    "Brown & white": "棕白",
    "Brown granite": "棕花岗岩",
    "Brown wood": "棕木",
    "Cake": "蛋糕",
    "Camel": "驼色",
    "Camphor-tree wood": "樟木",
    "Canned fish": "鱼罐头",
    "Canned fruit": "水果罐头",
    "Canned olives": "橄榄罐头",
    "Canned pasta sauce": "意面酱罐头",
    "Canned pet food": "宠物罐头",
    "Caramel mocha": "焦糖摩卡",
    "Carp": "鲤鱼",
    "Carrot": "胡萝卜",
    "Carrots": "胡萝卜",
    "Castle": "城堡",
    "Cat": "猫",
    "Caution": "警告",
    "Caution stripes": "警示条纹",
    "Cherry blossom": "樱花",
    "Cherry blossoms": "樱花",
    "Cherry brown": "樱桃棕",
    "Cherry wood": "樱桃木",
    "Chestnut": "栗子",
    "Chic flowers": "时尚花",
    "Chic white": "时尚白",
    "Chick": "小鸡",
    "Chicks": "小鸡",
    "Choco": "巧克力",
    "Chocolate": "巧克力",
    "Chocolate buttercream": "巧克力奶油",
    "Chocolate mint": "巧克力薄荷",
    "Chocolate swirl": "巧克力旋纹",
    "Citrus": "柑橘",
    "Classic camo": "经典迷彩",
    "Clay cake": "粘土蛋糕",
    "Clay dinosaur": "粘土恐龙",
    "Club activities": "社团活动",
    "Cocoa flavored": "可可味",
    "Colorful cake": "彩色蛋糕",
    "Colorful dinosaur": "彩色恐龙",
    "Colorful numbers": "彩色数字",
    "Colorful quilt": "彩色被子",
    "Colorful quilt design": "彩色被子图案",
    "Comics": "漫画",
    "Common pochard": "红头潜鸭",
    "Concrete": "混凝土",
    "Congee": "粥",
    "Constellations": "星座",
    "Construction ahead": "前方施工",
    "Construction warning": "施工警告",
    "Cool blue": "酷蓝",
    "Coral pink": "珊瑚粉",
    "Corn soup": "玉米汤",
    "Cosmo black": "宇宙黑",
    "Cranes": "鹤",
    "Cream stew": "奶油炖菜",
    "Cubes": "立方体",
    "Curry": "咖喱",
    "Cyan": "青色",
    "Damaged": "损坏",
    "Dark": "深色",
    "Dark blue": "深蓝色",
    "Dark brown": "深棕色",
    "Dark gray": "深灰色",
    "Dark green": "深绿色",
    "Dark red": "深红色",
    "Dark wood": "深色木",
    "Deep blue": "深蓝色",
    "Deep ocean": "深海",
    "Deep sea": "深海",
    "Denim with stripes": "条纹牛仔",
    "Dinosaur": "恐龙",
    "Dodgeball": "躲避球",
    "Dog": "狗",
    "Dot": "圆点",
    "Double sash": "双腰带",
    "Dragon": "龙",
    "Dreamy plaid": "梦幻格子",
    "Dried bamboo": "干竹",
    "Duck": "鸭子",
    "Elegant flowers": "优雅花",
    "Emerald & lime": "翡翠青柠",
    "Empty": "空",
    "Encyclopedia": "百科全书",
    "Energetic plaid": "活力格子",
    "Evergreen": "常青",
    "Fact-finding meeting": "调查会议",
    "Failed attempt": "失败尝试",
    "Fairy-tale house": "童话屋",
    "Fall harvest": "秋收",
    "Family": "家庭",
    "Fanciful quilted pattern": "奇幻拼布",
    "Fancy plaid": "精美格子",
    "Field of Flowers": "花田",
    "Fire red": "火红",
    "Fish": "鱼",
    "Fishing Spot": "钓鱼点",
    "Flame orange": "火焰橙",
    "Flowers": "花朵",
    "Foreign language": "外语",
    "Forest print": "森林印花",
    "Frog": "青蛙",
    "Fruits": "水果",
    "Fuchsia": "紫红色",
    "Garden": "花园",
    "Garnet": "石榴石",
    "Geometric pattern": "几何图案",
    "Gertie": "格蒂",
    "Giant snakehead": "大 snakehead",
    "Giant trevally": "珍鲹",
    "Girl": "女孩",
    "Gold & silver": "金银",
    "Gold bars": "金条",
    "Gold leaf": "金叶",
    "Golden yellow": "金黄色",
    "Goldfish": "金鱼",
    "Graffiti": "涂鸦",
    "Gray & blue": "灰蓝",
    "Gray & green": "灰绿",
    "Gray & white": "灰白",
    "Gray wood & tile": "灰木瓷砖",
    "Gray, white & light blue": "灰白浅蓝",
    "Greater scaup": "斑背潜鸭",
    "Green & black": "绿黑",
    "Green & blue": "绿蓝",
    "Green & navy": "绿藏青",
    "Green & orange": "绿橙",
    "Green & purple": "绿紫",
    "Green & red": "绿红",
    "Green & white": "绿白",
    "Green apple": "青苹果",
    "Green bamboo": "绿竹",
    "Green curry": "绿咖喱",
    "Green logo": "绿标志",
    "Green ribbons": "绿丝带",
    "Green roof": "绿屋顶",
    "Green smoothie": "绿色冰沙",
    "Green stripes": "绿条纹",
    "Green tea": "绿茶",
    "Green-striped necktie": "绿条纹领带",
    "Greige": "灰米色",
    "Handprints": "手印",
    "Hawk": "鹰",
    "Hibiscus flowers": "芙蓉花",
    "Home": "家",
    "Hot air balloons": "热气球",
    "Hot dog": "热狗",
    "Hot-and-sour soup": "酸辣汤",
    "Hungry gnome": "饥饿地精",
    "Ice": "冰",
    "Ice blue": "冰蓝",
    "Ice green": "冰绿",
    "Ice orange": "冰橙",
    "Ice pink": "冰粉",
    "Ice purple": "冰紫",
    "Ice yellow": "冰黄",
    "Illustration": "插画",
    "In progress": "进行中",
    "Indigo blue": "靛蓝",
    "Items": "物品",
    "Japanese literature": "日本文学",
    "Ketchup and mustard": "番茄酱芥末",
    "Kids' game": "儿童游戏",
    "Kiwifruit": "猕猴桃",
    "Kyoto in summer": "夏日京都",
    "La France": "法国",
    "Labeled": "有标签",
    "Laid-back gnome": "悠闲地精",
    "Language classroom": "语言教室",
    "Le Lectier": "Le Lectier 梨",
    "Leisure boat": "休闲船",
    "Lemon & white": "柠檬白",
    "Letter": "信件",
    "Light blue & black": "浅蓝黑",
    "Light blue & pink": "浅蓝粉",
    "Light blue & red": "浅蓝红",
    "Light blue & salmon pink": "浅蓝鲑鱼粉",
    "Light brown & black": "浅棕黑",
    "Lime & light blue": "青柠浅蓝",
    "Lime & pink": "青柠粉",
    "Lime & purple": "青柠紫",
    "Lime yellow": "青柠黄",
    "Literature": "文学",
    "Love": "爱",
    "Lumberjack": "伐木工",
    "M": "M",
    "Magenta": "洋红",
    "Mallard": "绿头鸭",
    "Mango": "芒果",
    "Maple": "枫木",
    "Marine": "海洋",
    "Marine blue": "海蓝",
    "Marine emerald": "海翡翠",
    "Marufukumaru - Bounty": "丸福丸-赏金",
    "Math": "数学",
    "Midnight": "午夜",
    "Minestrone": "蔬菜汤",
    "Mixed wood": "混合木",
    "Monochrome": "单色",
    "Monotone": "单色调",
    "Mosaic tile": "马赛克瓷砖",
    "Moss green": "苔藓绿",
    "Mossy": "苔藓",
    "Mossy stone": "苔藓石",
    "Mountain": "山",
    "Multicolor": "多彩",
    "Multiplication tables": "乘法表",
    "Muslin": "平纹细布",
    "Mustard": "芥末色",
    "Natural & green": "自然绿",
    "Natural & red": "自然红",
    "Natural & silver": "自然银",
    "Natural & white": "自然白",
    "Natural sand": "自然沙",
    "Navy & blue": "藏青蓝",
    "Navy & gray": "藏青灰",
    "Navy & red": "藏青红",
    "Navy blue": "藏蓝色",
    "Navy, light blue & pink": "藏青浅蓝粉",
    "Neon blue & neon red": "霓虹蓝红",
    "Nintenmaru - Big Catch": "任天丸-大渔",
    "No ads": "无广告",
    "No coating": "无涂层",
    "No Entry": "禁止进入",
    "No finish": "无饰面",
    "No Parking": "禁止停车",
    "Nostalgia": "怀旧",
    "Oak": "橡木",
    "Ocean blue": "海蓝",
    "Ocean creatures": "海洋生物",
    "Ochre": "赭石",
    "Octopus": "章鱼",
    "Off-white": "米白",
    "Old": "旧",
    "Olive": "橄榄",
    "Ongoing work": "进行中",
    "Ongoing work - Big bro": "进行中-大哥",
    "Ongoing work - Little bro": "进行中-小弟",
    "Orange & black": "橙黑",
    "Orange & blue": "橙蓝",
    "Orange & red": "橙红",
    "Orange & white": "橙白",
    "Orange wood": "橙木",
    "Orange, yellow & black": "橙黄黑",
    "Oranges": "橙子",
    "Orange-yellow": "橙黄",
    "Ordinary mushroom": "普通蘑菇",
    "Oribe-style": "织部风格",
    "Pacific Ocean": "太平洋",
    "Painter's palette": "调色板",
    "Pale blue": "淡蓝",
    "Pale green": "淡绿",
    "Pale orange": "淡橙",
    "Pale sky": "淡天蓝",
    "Parrot green": "鹦鹉绿",
    "Passion": "热情",
    "Passionate gnome": "热情的地精",
    "Pasta": "意面",
    "Peacock blue": "孔雀蓝",
    "Pearl": "珍珠",
    "Pearl white": "珍珠白",
    "Pears": "梨",
    "Periodic table": "元素周期表",
    "Pine": "松木",
    "Pink & purple": "粉紫",
    "Pink & yellow": "粉黄",
    "Pink with green ribbon": "粉绿丝带",
    "Pink wood": "粉木",
    "Pink-white": "粉白",
    "Pippa": "皮帕",
    "Pirate ship": "海盗船",
    "Pizza": "披萨",
    "Playtime": "游戏时间",
    "Plum": "李子",
    "Pop flowers": "流行花",
    "Pop pattern": "流行图案",
    "Powder white": "粉白",
    "Puppers": "小狗",
    "Purple & green": "紫绿",
    "Purple & orange": "紫橙",
    "Purple & pink": "紫粉",
    "Purple & yellow": "紫黄",
    "Purple sweet potato": "紫薯",
    "Purple-striped necktie": "紫条纹领带",
    "Quilted animals": "拼布动物",
    "Quilted pattern": "拼布图案",
    "Ratatouille": "炖菜",
    "Rattan": "藤条",
    "Rebel gnome": "叛逆地精",
    "Red & black": "红黑",
    "Red & blue": "红蓝",
    "Red & green": "红绿",
    "Red & light blue": "红浅蓝",
    "Red & orange": "红橙",
    "Red & pink": "红粉",
    "Red & white": "红白",
    "Red & yellow": "红黄",
    "Red apple": "红苹果",
    "Red brick": "红砖",
    "Red exit": "红出口",
    "Red logo": "红标志",
    "Red mushroom": "红蘑菇",
    "Red necktie": "红领带",
    "Red ribbons": "红丝带",
    "Red roof": "红屋顶",
    "Red snapper": "红鲷鱼",
    "Red stripes": "红条纹",
    "Red with hearts": "红心",
    "Red wood": "红木",
    "Red, white & blue": "红白蓝",
    "Reddish brown": "红棕",
    "Red-striped necktie": "红条纹领带",
    "Reference": "参考",
    "Reflective stripes": "反光条纹",
    "Reliable gnome": "可靠地精",
    "Resident Services": "居民服务",
    "Retro ride": "复古骑行",
    "Ring": "戒指",
    "Roary": "罗里",
    "Roasting marshmallows": "烤棉花糖",
    "Rose gold": "玫瑰金",
    "Rose pink": "玫瑰粉",
    "Rose red & navy": "玫瑰红藏青",
    "Royal": "皇家",
    "Royal coach": "皇家马车",
    "Ruby red": "红宝石红",
    "Rusted iron": "锈铁",
    "Sales meeting": "销售会议",
    "Sandalwood": "檀香木",
    "Sash": "腰带",
    "Savannah": "草原",
    "Saxon blue": "萨克森蓝",
    "Schedule": "日程",
    "Sepia": "深褐色",
    "Shabby": "破旧",
    "Sheep": "绵羊",
    "Shocking pink": " shocking 粉",
    "Shop": "商店",
    "Signature": "签名",
    "Silver & blue": "银蓝",
    "Silver & green": "银绿",
    "Simple house": "简单房屋",
    "Simple path game": "简单路径游戏",
    "Simple pattern": "简单图案",
    "Sky blue": "天蓝",
    "Sleepy gnome": "瞌睡地精",
    "Slippery": "滑",
    "Smoke-cured bamboo": "烟熏竹",
    "Snow": "雪",
    "Snow camouflage": "雪地迷彩",
    "Soccer ball": "足球",
    "Soda": "苏打",
    "Southwestern flair": "西南风情",
    "Souvenir": "纪念品",
    "Space silver": "太空银",
    "Splatter up": "飞溅",
    "Sponsor": "赞助商",
    "Sports": "运动",
    "Spot-billed": "斑嘴",
    "Spotted": "斑点",
    "Sprightly gnome": "活泼地精",
    "Spring blooming": "春花",
    "Squid": "鱿鱼",
    "Stacks of cash": "现金堆",
    "Stainless": "不锈钢",
    "Stainless steel": "不锈钢",
    "Standard": "标准",
    "Star": "星星",
    "Stars": "星星",
    "Steamer duck": "蒸汽鸭",
    "Still Life": "静物",
    "Stone house": "石屋",
    "Stop": "停止",
    "Strange mushroom": "奇怪蘑菇",
    "Strategy meeting": "战略会议",
    "Strawberries": "草莓",
    "Strawberry & flowers": "草莓花",
    "Strawberry buttercream": "草莓奶油",
    "Strawberry flavored": "草莓味",
    "Strawberry swirl": "草莓旋纹",
    "Street with Trees": "树街",
    "Striped house": "条纹屋",
    "Stripes": "条纹",
    "Sunburst": "日爆",
    "Sunset": "日落",
    "Surprised gnome": "惊讶地精",
    "Sweet plaid": "甜美格子",
    "Sweet Roses": "甜玫瑰",
    "Tailors": "裁缝",
    "Tea": "茶",
    "Teak": "柚木",
    "Teddy bear": "泰迪熊",
    "Territory game": "领地游戏",
    "Textbook": "教科书",
    "The Mesozoic world": "中生代世界",
    "The ocean blue": "海洋蓝",
    "Tiger": "老虎",
    "Tomatoes": "番茄",
    "Topaz": "黄玉",
    "Trading ship": "贸易船",
    "Tree peonies": "牡丹",
    "Trees": "树",
    "Tricolored": "三色",
    "Tropical": "热带",
    "Tsurukamemaru - Longevity": "鹤龟丸-长寿",
    "Tulip": "郁金香",
    "Turquoise": "绿松石",
    "Tweed": "粗花呢",
    "Twilight": "暮光",
    "Two-toned numbers": "双色数字",
    "Two-toned tile": "双色瓷砖",
    "Unfinished wood": "未完工木",
    "Unglazed": "未上釉",
    "University": "大学",
    "Unlabeled can": "无标签罐头",
    "Uomasamaru III - Launch": "鱼政丸三号-发射",
    "Vanilla & chocolate": "香草巧克力",
    "Vanilla flavored": "香草味",
    "Veggie sauté": "炒蔬菜",
    "Vermilion": "朱砂",
    "Vertical stripes": "竖条纹",
    "Vivid": "鲜艳",
    "Volleyball": "排球",
    "Walnut": "胡桃木",
    "Warning": "警告",
    "Washed out": "褪色",
    "Watermelon": "西瓜",
    "Western literature": "西方文学",
    "Whipped-cream topping": "鲜奶油 topping",
    "White & blue": "白蓝",
    "White & red": "白红",
    "White & silver": "白银",
    "White birch": "白桦",
    "White granite": "白花岗岩",
    "White marble": "白大理石",
    "White mushroom": "白蘑菇",
    "White peach": "白桃",
    "White sand": "白沙",
    "White with blue ribbon": "白蓝丝带",
    "White wood & tile": "白木瓷砖",
    "White, blue & green": "白蓝绿",
    "White, yellow & red": "白黄红",
    "White-striped necktie": "白条纹领带",
    "Wild": "野生",
    "Win or lose": "输赢",
    "Winter": "冬季",
    "Wisteria": "紫藤",
    "With ads": "有广告",
    "Wood grain": "木纹",
    "Wood house": "木屋",
    "Wooden": "木质",
    "Words of wisdom": "智慧之言",
    "Writer's block": "写作障碍",
    "Yellow & avocado": "黄牛油果",
    "Yellow & black": "黄黑",
    "Yellow & blue": "黄蓝",
    "Yellow & navy": "黄藏青",
    "Yellow & orange": "黄橙",
    "Yellow & purple": "黄紫",
    "Yellow & red": "黄红",
    "Yellow amber": "黄琥珀",
    "Yellow mushroom": "黄蘑菇",
    "Yellow peach": "黄桃",
    "Yellow with red ribbon": "黄红丝带",
    "Yellow-green": "黄绿",
    "Zebra": "斑马",
    "Zelkova wood": "榉木"
};
